from metacog.epistemic import (
    AuditEntry,
    DEFAULT_OBSERVATOR_ID,
    EpistemicState,
    LaunderingError,
    Observation,
    Point,
    PointKind,
    SourceClass,
    apply_observation,
    assign_status,
    process_observation,
)
from metacog.observator import (
    DelegationEvent,
    Observator,
    ObservatorView,
    cluster_observations_by_content,
    delegate_query,
    detect_polarization,
    polarization_score,
    select_observators,
    spawn_observators_by_clustering,
    spawn_observators_from_polarization,
)
from metacog.geometry import retrieve_for_observator
from metacog.defaults import NoOpExecutor, SimpleEncoder, SimpleLLM
from metacog.memory import Memory
from metacog.compression import (
    CompressionEvent,
    CompressionOpportunity,
    CompressionResult,
    EagerCompressionReport,
    compress_chain,
    compress_trajectory,
    detect_chasles_opportunities,
    straight_ratio,
)
from metacog.execution import (
    ExecutionOutcome,
    ExecutionRecord,
    ExecutionResult,
    ExecutorProtocol,
    execute_action,
)
from metacog.reasoning import (
    COS_STABLE,
    ReasoningLLM,
    ReasoningStep,
    ReasoningTrajectory,
    reason,
)
from metacog.audit import (
    NoLaunderingInvariant,
    assert_no_laundering,
    audit,
    inputs_of_A,
)
from metacog.geometry import (
    apply_exile,
    apply_pull,
    compute_centroid,
    cosine,
    decay_factor,
    distance,
    effective_embedding,
    k_nearest,
    retrieve,
    vec_norm,
)
from metacog.collision import (
    CollisionEvent,
    CollisionResult,
    Encoder,
    LLMExtractor,
    MAX_CASCADE_ITERATIONS,
    SleepCycleReport,
    collision_threshold,
    detect_collisions,
    resolve_collision,
    sleep_cycle_collisions,
)
from metacog.detectors import (
    COS_HIGHLY_SIMILAR,
    COS_MODERATELY_SIMILAR,
    ConversationLog,
    TurnRecord,
    analyze_user_turn,
    detect_contradiction,
    detect_continuation,
    detect_corroboration,
    detect_reformulation,
    detect_repetition_of_need,
)

__all__ = [
    # epistemic
    "AuditEntry",
    "EpistemicState",
    "LaunderingError",
    "Observation",
    "Point",
    "PointKind",
    "SourceClass",
    "DEFAULT_OBSERVATOR_ID",
    "apply_observation",
    "assign_status",
    "process_observation",
    # observators
    "Observator",
    "ObservatorView",
    "select_observators",
    "DelegationEvent",
    "cluster_observations_by_content",
    "delegate_query",
    "detect_polarization",
    "polarization_score",
    "spawn_observators_from_polarization",
    "spawn_observators_by_clustering",
    "retrieve_for_observator",
    # defaults + top-level wrapper
    "NoOpExecutor",
    "SimpleEncoder",
    "SimpleLLM",
    "Memory",
    # compression (Chasles)
    "CompressionEvent",
    "CompressionOpportunity",
    "CompressionResult",
    "EagerCompressionReport",
    "compress_chain",
    "compress_trajectory",
    "detect_chasles_opportunities",
    "straight_ratio",
    # execution
    "ExecutionOutcome",
    "ExecutionRecord",
    "ExecutionResult",
    "ExecutorProtocol",
    "execute_action",
    # reasoning
    "COS_STABLE",
    "ReasoningLLM",
    "ReasoningStep",
    "ReasoningTrajectory",
    "reason",
    # audit
    "NoLaunderingInvariant",
    "assert_no_laundering",
    "audit",
    "inputs_of_A",
    # geometry
    "apply_pull",
    "cosine",
    "decay_factor",
    "distance",
    "effective_embedding",
    "apply_exile",
    "compute_centroid",
    "k_nearest",
    "retrieve",
    "vec_norm",
    # collision
    "CollisionEvent",
    "CollisionResult",
    "Encoder",
    "LLMExtractor",
    "MAX_CASCADE_ITERATIONS",
    "SleepCycleReport",
    "collision_threshold",
    "detect_collisions",
    "resolve_collision",
    "sleep_cycle_collisions",
    # detectors
    "COS_HIGHLY_SIMILAR",
    "COS_MODERATELY_SIMILAR",
    "ConversationLog",
    "TurnRecord",
    "analyze_user_turn",
    "detect_contradiction",
    "detect_continuation",
    "detect_corroboration",
    "detect_reformulation",
    "detect_repetition_of_need",
]
