from metacog.epistemic import (
    AuditEntry,
    EpistemicState,
    LaunderingError,
    Observation,
    Point,
    PointKind,
    SourceClass,
    apply_observation,
    assign_status,
    process_observation,
)
from metacog.compression import (
    CompressionEvent,
    CompressionOpportunity,
    CompressionResult,
    EagerCompressionReport,
    compress_chain,
    compress_trajectory,
    detect_chasles_opportunities,
    straight_ratio,
)
from metacog.audit import (
    NoLaunderingInvariant,
    assert_no_laundering,
    audit,
    inputs_of_A,
)
from metacog.geometry import (
    apply_exile,
    apply_pull,
    compute_centroid,
    cosine,
    decay_factor,
    distance,
    effective_embedding,
    k_nearest,
    retrieve,
    vec_norm,
)
from metacog.collision import (
    CollisionEvent,
    CollisionResult,
    Encoder,
    LLMExtractor,
    MAX_CASCADE_ITERATIONS,
    SleepCycleReport,
    collision_threshold,
    detect_collisions,
    resolve_collision,
    sleep_cycle_collisions,
)
from metacog.detectors import (
    COS_HIGHLY_SIMILAR,
    COS_MODERATELY_SIMILAR,
    ConversationLog,
    TurnRecord,
    analyze_user_turn,
    detect_contradiction,
    detect_continuation,
    detect_corroboration,
    detect_reformulation,
    detect_repetition_of_need,
)

__all__ = [
    # epistemic
    "AuditEntry",
    "EpistemicState",
    "LaunderingError",
    "Observation",
    "Point",
    "PointKind",
    "SourceClass",
    "apply_observation",
    "assign_status",
    "process_observation",
    # compression (Chasles)
    "CompressionEvent",
    "CompressionOpportunity",
    "CompressionResult",
    "EagerCompressionReport",
    "compress_chain",
    "compress_trajectory",
    "detect_chasles_opportunities",
    "straight_ratio",
    # audit
    "NoLaunderingInvariant",
    "assert_no_laundering",
    "audit",
    "inputs_of_A",
    # geometry
    "apply_pull",
    "cosine",
    "decay_factor",
    "distance",
    "effective_embedding",
    "apply_exile",
    "compute_centroid",
    "k_nearest",
    "retrieve",
    "vec_norm",
    # collision
    "CollisionEvent",
    "CollisionResult",
    "Encoder",
    "LLMExtractor",
    "MAX_CASCADE_ITERATIONS",
    "SleepCycleReport",
    "collision_threshold",
    "detect_collisions",
    "resolve_collision",
    "sleep_cycle_collisions",
    # detectors
    "COS_HIGHLY_SIMILAR",
    "COS_MODERATELY_SIMILAR",
    "ConversationLog",
    "TurnRecord",
    "analyze_user_turn",
    "detect_contradiction",
    "detect_continuation",
    "detect_corroboration",
    "detect_reformulation",
    "detect_repetition_of_need",
]
